# Generated by Django 3.2.4 on 2023-09-03 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_table1_models_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table1_models',
            old_name='user_id',
            new_name='user_name',
        ),
    ]
